if obj_player.debugstats
{
	draw_set_font(global.font_small)
	var rm = string_upper(room_get_name(room))
	var statename = string_upper(obj_player.state)
	var spr = string_upper(sprite_get_name(obj_player.sprite_index))
	draw_set_valign(fa_middle)
	draw_set_color(c_white)
	draw_set_halign(fa_left)
	draw_text(32, (258), ("CHARACTER: " + string(obj_player.character)))
	draw_text(32, (240), ("IMAGE_INDEX: " +  string(obj_player.image_index)))
	draw_text(32, (216), ("IMAGE_SPEED: " +  string(obj_player.image_speed)))
	draw_text(32, (192), ("X: " + string(x)))
	draw_text(32, (168), ("Y: " + string(y)))
	draw_text(32, (144), ("REAL HSP: " + string(obj_player.movespeed)))
	draw_text(32, (120), ("HSP: " + string(obj_player.hsp)))
	draw_text(32, (96),  ("VSP: " + string(obj_player.vsp)))
	draw_text(32, (72),  ("STATE: " + statename))
	draw_text(32, (48),  ("SPRITE_INDEX: " + spr))
	draw_text(32, (24),  ("ROOM: " + rm))
	pal_swap_set(obj_player.spr_palette, obj_player.paletteselect)
	draw_sprite_ext(obj_player.sprite_index,obj_player.image_index,32 + 50, (380 + 50),2,2,image_angle,c_white,1)
	shader_reset()
}